### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4954](https://github.com/atypon/test_public/pull/4954)), master ([PR#4955](https://github.com/atypon/test_public/pull/4955))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4953](https://github.com/atypon/test_public/pull/4953) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 76dbc3cafcf8ee9ae163dc2ed87416e25fa1c752 ([link](https://github.com/atypon/test_public/commit/76dbc3cafcf8ee9ae163dc2ed87416e25fa1c752))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid efda5d32b74ad58a808807a7123fc2ef6e9454c9 ([link](https://github.com/atypon/test_public/commit/efda5d32b74ad58a808807a7123fc2ef6e9454c9))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 06c26dac20b9900e828cd278578893bf77d31667 ([link](https://github.com/atypon/test_public/commit/06c26dac20b9900e828cd278578893bf77d31667))

**Pull request merged**
