### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5111](https://github.com/atypon/test_public/pull/5111)), master ([PR#5112](https://github.com/atypon/test_public/pull/5112))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5110](https://github.com/atypon/test_public/pull/5110) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 84f05307878063f1783e9ca198d7abb94e16d9ff ([link](https://github.com/atypon/test_public/commit/84f05307878063f1783e9ca198d7abb94e16d9ff))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 717394934c674629eb2b37708afa5a0587ade9ba ([link](https://github.com/atypon/test_public/commit/717394934c674629eb2b37708afa5a0587ade9ba))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 8b59b31772d511f5dd462fb7dea19bc8b3bb2646 ([link](https://github.com/atypon/test_public/commit/8b59b31772d511f5dd462fb7dea19bc8b3bb2646))

**Pull request merged**
