### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4769](https://github.com/atypon/test_public/pull/4769)), master ([PR#4770](https://github.com/atypon/test_public/pull/4770))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4768](https://github.com/atypon/test_public/pull/4768) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid b9bffdde140c07e685d7cdd39f1eb1ed898b93a6 ([link](https://github.com/atypon/test_public/commit/b9bffdde140c07e685d7cdd39f1eb1ed898b93a6))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 0a6541b375ea35f42dc1c2148ce9158c4a4e20fe ([link](https://github.com/atypon/test_public/commit/0a6541b375ea35f42dc1c2148ce9158c4a4e20fe))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid ae510321d8d9f78585e645ee089e91fe8251e2b6 ([link](https://github.com/atypon/test_public/commit/ae510321d8d9f78585e645ee089e91fe8251e2b6))

**Pull request merged**
