### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4586](https://github.com/atypon/test_public/pull/4586)), master ([PR#4587](https://github.com/atypon/test_public/pull/4587))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1734](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1734/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4585](https://github.com/atypon/test_public/pull/4585) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 0ed0b5e90c2e2f7fbfb92d7900aa4eb3cbca75fb ([link](https://github.com/atypon/test_public/commit/0ed0b5e90c2e2f7fbfb92d7900aa4eb3cbca75fb))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 80fd8e4f6d827d13b46d418f20c8a63f18c6d62e ([link](https://github.com/atypon/test_public/commit/80fd8e4f6d827d13b46d418f20c8a63f18c6d62e))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 482857990eaf38dd66de23d88e47454b92a81fda ([link](https://github.com/atypon/test_public/commit/482857990eaf38dd66de23d88e47454b92a81fda))

**Pull request merged**
