### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5265](https://github.com/atypon/test_public/pull/5265)), master ([PR#5266](https://github.com/atypon/test_public/pull/5266))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5264](https://github.com/atypon/test_public/pull/5264) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid b63641fc819387d9725674f45c6c4060e1658b6a ([link](https://github.com/atypon/test_public/commit/b63641fc819387d9725674f45c6c4060e1658b6a))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid d1561e2e86e8fc25d4c2dd56c6408e4a34a97fd2 ([link](https://github.com/atypon/test_public/commit/d1561e2e86e8fc25d4c2dd56c6408e4a34a97fd2))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid db435c732db243c60b8613148b5e88f6f9e2f705 ([link](https://github.com/atypon/test_public/commit/db435c732db243c60b8613148b5e88f6f9e2f705))

**Pull request merged**
