### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4675](https://github.com/atypon/test_public/pull/4675)), master ([PR#4676](https://github.com/atypon/test_public/pull/4676))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1770](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1770/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4674](https://github.com/atypon/test_public/pull/4674) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 1df64f3e286bbfc3c2d9f4e624e7168063c0bc4b ([link](https://github.com/atypon/test_public/commit/1df64f3e286bbfc3c2d9f4e624e7168063c0bc4b))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 35cf81b1a21ed5bfa1f93ba090081cc4716a75c1 ([link](https://github.com/atypon/test_public/commit/35cf81b1a21ed5bfa1f93ba090081cc4716a75c1))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 759fbb69f0fae0932d225f250dab170828c1a1f0 ([link](https://github.com/atypon/test_public/commit/759fbb69f0fae0932d225f250dab170828c1a1f0))

**Pull request merged**
