### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4983](https://github.com/atypon/test_public/pull/4983)), master ([PR#4984](https://github.com/atypon/test_public/pull/4984))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4982](https://github.com/atypon/test_public/pull/4982) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid e00c6cf9721a7dc494bd17ae5504443b3770f777 ([link](https://github.com/atypon/test_public/commit/e00c6cf9721a7dc494bd17ae5504443b3770f777))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 63a7b726ff569f15009d799b27f9292d349e09b2 ([link](https://github.com/atypon/test_public/commit/63a7b726ff569f15009d799b27f9292d349e09b2))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 9f0a2ac85c1c0945c6fedcca8bd1e498e6e1ab8e ([link](https://github.com/atypon/test_public/commit/9f0a2ac85c1c0945c6fedcca8bd1e498e6e1ab8e))

**Pull request merged**
