### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4817](https://github.com/atypon/test_public/pull/4817)), master ([PR#4818](https://github.com/atypon/test_public/pull/4818))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4816](https://github.com/atypon/test_public/pull/4816) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 0be5e6c10676dba6759483daf96934db681a4d4b ([link](https://github.com/atypon/test_public/commit/0be5e6c10676dba6759483daf96934db681a4d4b))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid f12140513b80f65a9dc8fbea431cc477a43869b7 ([link](https://github.com/atypon/test_public/commit/f12140513b80f65a9dc8fbea431cc477a43869b7))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 56ac84e6b202132035015a8fd11d8c96b085e5a9 ([link](https://github.com/atypon/test_public/commit/56ac84e6b202132035015a8fd11d8c96b085e5a9))

**Pull request merged**
