### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4974](https://github.com/atypon/test_public/pull/4974)), master ([PR#4975](https://github.com/atypon/test_public/pull/4975))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1854](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1854/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4973](https://github.com/atypon/test_public/pull/4973) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 203be38566eae99345984d5a90b08bd730b22c4c ([link](https://github.com/atypon/test_public/commit/203be38566eae99345984d5a90b08bd730b22c4c))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 539af1fdfec6f5140670bd5e77602e7860cbe415 ([link](https://github.com/atypon/test_public/commit/539af1fdfec6f5140670bd5e77602e7860cbe415))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid bd2a21ba7493a303868fb5a9394652de7fa7db72 ([link](https://github.com/atypon/test_public/commit/bd2a21ba7493a303868fb5a9394652de7fa7db72))

**Pull request merged**
