### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4917](https://github.com/atypon/test_public/pull/4917)), master ([PR#4918](https://github.com/atypon/test_public/pull/4918))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4916](https://github.com/atypon/test_public/pull/4916) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid de0b5fe14ff2efc4cb2eac825f3ab76ed77b64ef ([link](https://github.com/atypon/test_public/commit/de0b5fe14ff2efc4cb2eac825f3ab76ed77b64ef))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid c94537b68917c60e141d05979c24e42009c76f34 ([link](https://github.com/atypon/test_public/commit/c94537b68917c60e141d05979c24e42009c76f34))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 16e7bb5f5bdfd91cf506f65daea7eb1e528bc866 ([link](https://github.com/atypon/test_public/commit/16e7bb5f5bdfd91cf506f65daea7eb1e528bc866))

**Pull request merged**
