### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5446](https://github.com/atypon/test_public/pull/5446)), master ([PR#5447](https://github.com/atypon/test_public/pull/5447))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #2004](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/2004/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5445](https://github.com/atypon/test_public/pull/5445) complete:

atypon/test_public Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid e61f2fe25c12db69c20187f76cc0577f04f30634 ([link](https://github.com/atypon/test_public/commit/e61f2fe25c12db69c20187f76cc0577f04f30634))
atypon/test_public Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid c9335dde3a6e89ace68a131a9fb9174da3229c39 ([link](https://github.com/atypon/test_public/commit/c9335dde3a6e89ace68a131a9fb9174da3229c39))
atypon/test_public Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid d16e61acd2eae03639d4df5a9bc39d39b05bca51 ([link](https://github.com/atypon/test_public/commit/d16e61acd2eae03639d4df5a9bc39d39b05bca51))

**Pull request merged**
