### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5307](https://github.com/atypon/test_public/pull/5307)), master ([PR#5308](https://github.com/atypon/test_public/pull/5308))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5306](https://github.com/atypon/test_public/pull/5306) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 977e95675dcdc88c59cceac7c51d2f9b0c9f9523 ([link](https://github.com/atypon/test_public/commit/977e95675dcdc88c59cceac7c51d2f9b0c9f9523))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 95372e906184863e416d7dd931e47048e487ff8b ([link](https://github.com/atypon/test_public/commit/95372e906184863e416d7dd931e47048e487ff8b))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 9a88d019bdb9616cd7d8ae4296ebe4035744b1df ([link](https://github.com/atypon/test_public/commit/9a88d019bdb9616cd7d8ae4296ebe4035744b1df))

**Pull request merged**
