### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4999](https://github.com/atypon/test_public/pull/4999)), master ([PR#5000](https://github.com/atypon/test_public/pull/5000))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4998](https://github.com/atypon/test_public/pull/4998) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 7f8f1d884759af855785e5cd9539cf2f6093cdc3 ([link](https://github.com/atypon/test_public/commit/7f8f1d884759af855785e5cd9539cf2f6093cdc3))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid dd1e92166111eb064e1bcf268e64320f8d3788ea ([link](https://github.com/atypon/test_public/commit/dd1e92166111eb064e1bcf268e64320f8d3788ea))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid c86ba67d81848526fe623aad6790982ac5b15cbf ([link](https://github.com/atypon/test_public/commit/c86ba67d81848526fe623aad6790982ac5b15cbf))

**Pull request merged**
