### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: 
generatingPulls: true

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1689](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1689/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
Failed to create merge pull for SG-1730 failed with error: Failed to create pull request for 4537: Failed to get pull requests (prgql: pr_4538:pullRequest(number: 4538) {
                
            state
            merged
            author {
                login
            }
            mergeable
            url
            updatedAt
            assignees(first:10) {
                nodes {
                    login
                }
            }
            number
            body
            commits(last: 100){
                nodes {
                    commit {
                        commitUrl
                        oid
                        author {
                            email
                            name
                            user {
                                login
                            }
                        }
                        status {
                            state
                            contexts {
                                state
                                targetUrl
                                description
                                context
                            }
                        }
                    }
                }
            }
            body
            title
            baseRefName
            baseRefOid
            headRefName
            headRefOid
            mergedBy {
                login
            }
            files(first:100) {
                nodes {
                    path
                }
            }
            reviews(first:100) {
                nodes {
                    author {
                        login
                    }
                    body
                    state
                }
            }
            reviewRequests(first:100) {
                nodes {
                    requestedReviewer {
                        ... on User {
                            login
                        }
                    }
                }
            }
            comments(last:100) {
                nodes {
                    databaseId
                    author {
                        login
                    }
                    body
                    reactions(last:10) {
                        nodes {
                            user {
                                login
                            }
                            content
                        }
                    }
                }
            }
        
            }): Cannot read property 'repository' of undefined

**Pull request closed without merging**
