### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5711](https://github.com/atypon/test_public/pull/5711)), master ([PR#5712](https://github.com/atypon/test_public/pull/5712))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
[GitBot] *MERGED* [atypon/test_public#5710](https://github.com/atypon/test_public/pull/5710) into branches: [SG-1730](https://github.com/atypon/test_public/commits/SG-1730) ([3d8721f](https://github.com/atypon/test_public/commit/3d8721f2ce2145c952c7d1f7c9ee9796bc22a06c)), [master](https://github.com/atypon/test_public/commits/master) ([98af0f3](https://github.com/atypon/test_public/commit/98af0f3e37d7e0b63daf56738c700dbbfc9eed98)), [SG-1720](https://github.com/atypon/test_public/commits/SG-1720) ([4ef9ddf](https://github.com/atypon/test_public/commit/4ef9ddf31ed31e5e3bd99bb2ea8c9f8e838942de))

**Pull request merged**
