### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4581](https://github.com/atypon/test_public/pull/4581)), master ([PR#4582](https://github.com/atypon/test_public/pull/4582))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1729](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1729/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4580](https://github.com/atypon/test_public/pull/4580) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid ecaeea2b5c6fc5f33921fe22ae1d4c706013c8b5 ([link](https://github.com/atypon/test_public/commit/ecaeea2b5c6fc5f33921fe22ae1d4c706013c8b5))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 450f003181ab5bb1d7d110d771849f1421f4bde5 ([link](https://github.com/atypon/test_public/commit/450f003181ab5bb1d7d110d771849f1421f4bde5))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid e711981e52652c53d03122e4c16f51165d945c25 ([link](https://github.com/atypon/test_public/commit/e711981e52652c53d03122e4c16f51165d945c25))

**Pull request merged**
