### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5276](https://github.com/atypon/test_public/pull/5276)), master ([PR#5277](https://github.com/atypon/test_public/pull/5277))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5275](https://github.com/atypon/test_public/pull/5275) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid eb409ab9f3ffe53fb9a3e258914d4a6d96ad8c1b ([link](https://github.com/atypon/test_public/commit/eb409ab9f3ffe53fb9a3e258914d4a6d96ad8c1b))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 1f692fc1db23b2d7e725112a2c50658e69cb8117 ([link](https://github.com/atypon/test_public/commit/1f692fc1db23b2d7e725112a2c50658e69cb8117))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid a30c5620bf643c9c362d785eea7ffb1a2ef9543b ([link](https://github.com/atypon/test_public/commit/a30c5620bf643c9c362d785eea7ffb1a2ef9543b))

**Pull request merged**
