### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4684](https://github.com/atypon/test_public/pull/4684)), master ([PR#4685](https://github.com/atypon/test_public/pull/4685))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4683](https://github.com/atypon/test_public/pull/4683) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 035fe2a638ff37a090ec3c36966d8dc58666bef2 ([link](https://github.com/atypon/test_public/commit/035fe2a638ff37a090ec3c36966d8dc58666bef2))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 66cf0e43cc7159719d585b8520d8dd147cb109ea ([link](https://github.com/atypon/test_public/commit/66cf0e43cc7159719d585b8520d8dd147cb109ea))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 8b9e4ee1992dbfeb9756e5d51b6a9798fc94d948 ([link](https://github.com/atypon/test_public/commit/8b9e4ee1992dbfeb9756e5d51b6a9798fc94d948))

**Pull request merged**
