### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5119](https://github.com/atypon/test_public/pull/5119)), master ([PR#5120](https://github.com/atypon/test_public/pull/5120))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5118](https://github.com/atypon/test_public/pull/5118) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 80856cc5a5d84112510357197ed77b34902a0c7b ([link](https://github.com/atypon/test_public/commit/80856cc5a5d84112510357197ed77b34902a0c7b))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 1a3810738f48dfd43f38d121cad82ccfe9d8426e ([link](https://github.com/atypon/test_public/commit/1a3810738f48dfd43f38d121cad82ccfe9d8426e))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid daa4f6add395c2fe828505dd11fd03ef5a484657 ([link](https://github.com/atypon/test_public/commit/daa4f6add395c2fe828505dd11fd03ef5a484657))

**Pull request merged**
