### PR TITLE
NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: devbranch ([PR#4961](https://github.com/atypon/test_public/pull/4961)), master ([PR#4962](https://github.com/atypon/test_public/pull/4962))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pull:devbranch

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4960](https://github.com/atypon/test_public/pull/4960) complete:

Branch devbranch ([link](https://github.com/atypon/test_public/commits/devbranch)): cid 296cae671314be124d98951860095b270b7693e9 ([link](https://github.com/atypon/test_public/commit/296cae671314be124d98951860095b270b7693e9))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid dfec65b8a671afb9028b82dedbeb1644ce225c02 ([link](https://github.com/atypon/test_public/commit/dfec65b8a671afb9028b82dedbeb1644ce225c02))
Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 59fd735573c85372cdbb96a31b4c7a5a5b61cf02 ([link](https://github.com/atypon/test_public/commit/59fd735573c85372cdbb96a31b4c7a5a5b61cf02))

**Pull request merged**
