### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4790](https://github.com/atypon/test_public/pull/4790)), master ([PR#4791](https://github.com/atypon/test_public/pull/4791))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1803](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1803/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4789](https://github.com/atypon/test_public/pull/4789) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 99a5050018525661771ef87b6acbef380f183e71 ([link](https://github.com/atypon/test_public/commit/99a5050018525661771ef87b6acbef380f183e71))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 75a4cdb9ec06edd45b23b0a6d880080c699af770 ([link](https://github.com/atypon/test_public/commit/75a4cdb9ec06edd45b23b0a6d880080c699af770))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 84baff50d7522e81bb10cd926ac651c954d5918c ([link](https://github.com/atypon/test_public/commit/84baff50d7522e81bb10cd926ac651c954d5918c))

**Pull request merged**
