### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5199](https://github.com/atypon/test_public/pull/5199)), master ([PR#5200](https://github.com/atypon/test_public/pull/5200))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5198](https://github.com/atypon/test_public/pull/5198) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 1e1862240def9f458be0c5c8c4fd8a494cc5541a ([link](https://github.com/atypon/test_public/commit/1e1862240def9f458be0c5c8c4fd8a494cc5541a))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid bcce46d5be8533c5ec27ba553352f95801dfc7bb ([link](https://github.com/atypon/test_public/commit/bcce46d5be8533c5ec27ba553352f95801dfc7bb))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 0ac92e1f913bac81cd1a4127e90192b49fab5469 ([link](https://github.com/atypon/test_public/commit/0ac92e1f913bac81cd1a4127e90192b49fab5469))

**Pull request merged**
