### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5693](https://github.com/atypon/test_public/pull/5693)), master ([PR#5694](https://github.com/atypon/test_public/pull/5694))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] *MERGED* [atypon/test_public#5692](https://github.com/atypon/test_public/pull/5692) into branches: [SG-1730](https://github.com/atypon/test_public/commits/SG-1730) ([d03aa45](https://github.com/atypon/test_public/commit/d03aa45468121e2404ba5e09502ef93401593cf7)), [master](https://github.com/atypon/test_public/commits/master) ([8dd0fbe](https://github.com/atypon/test_public/commit/8dd0fbe738b83724a3443a3a0a908c7468836101)), [SG-1720](https://github.com/atypon/test_public/commits/SG-1720) ([232038c](https://github.com/atypon/test_public/commit/232038ce0a4f534a8aadf7febe4d93c18ed143d0))

**Pull request merged**
