### PR TITLE
NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: devbranch ([PR#4820](https://github.com/atypon/test_public/pull/4820)), master ([PR#4821](https://github.com/atypon/test_public/pull/4821))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pull:devbranch

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4819](https://github.com/atypon/test_public/pull/4819) complete:

Branch devbranch ([link](https://github.com/atypon/test_public/commits/devbranch)): cid 3d2511dc5bb8c1d9a163432d799c9a40eb0624e7 ([link](https://github.com/atypon/test_public/commit/3d2511dc5bb8c1d9a163432d799c9a40eb0624e7))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid f7c1fd1f84ad8107ef314b44694b7bee9bfc7881 ([link](https://github.com/atypon/test_public/commit/f7c1fd1f84ad8107ef314b44694b7bee9bfc7881))
Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid e5e35862fdc9407ff7d2827c7762aa36bef1b63a ([link](https://github.com/atypon/test_public/commit/e5e35862fdc9407ff7d2827c7762aa36bef1b63a))

**Pull request merged**
