### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4593](https://github.com/atypon/test_public/pull/4593)), master ([PR#4594](https://github.com/atypon/test_public/pull/4594))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1739](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1739/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4592](https://github.com/atypon/test_public/pull/4592) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid d7ca538d6d46049b8425fe6e4d5e09540ca03b87 ([link](https://github.com/atypon/test_public/commit/d7ca538d6d46049b8425fe6e4d5e09540ca03b87))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid ca91b3cce7c0d3b2a5738f569e34831382442ef6 ([link](https://github.com/atypon/test_public/commit/ca91b3cce7c0d3b2a5738f569e34831382442ef6))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 648da06c093f72ccc3f94aece071335d7c6437c2 ([link](https://github.com/atypon/test_public/commit/648da06c093f72ccc3f94aece071335d7c6437c2))

**Pull request merged**
