### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4799](https://github.com/atypon/test_public/pull/4799)), master ([PR#4800](https://github.com/atypon/test_public/pull/4800))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4798](https://github.com/atypon/test_public/pull/4798) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 3d8d32ee4841a0a2fe92bdc4f7e049a261556b0e ([link](https://github.com/atypon/test_public/commit/3d8d32ee4841a0a2fe92bdc4f7e049a261556b0e))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 5cf450b4cb82fcd5f1a2fb52cd1977bc53ae6c0c ([link](https://github.com/atypon/test_public/commit/5cf450b4cb82fcd5f1a2fb52cd1977bc53ae6c0c))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 9b2ee2877d9d142b63070ea1e8eb4d854e167ae0 ([link](https://github.com/atypon/test_public/commit/9b2ee2877d9d142b63070ea1e8eb4d854e167ae0))

**Pull request merged**
