### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5168](https://github.com/atypon/test_public/pull/5168)), master ([PR#5169](https://github.com/atypon/test_public/pull/5169))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5167](https://github.com/atypon/test_public/pull/5167) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 89b5d9dcc020d94caea77a89889c7263106da077 ([link](https://github.com/atypon/test_public/commit/89b5d9dcc020d94caea77a89889c7263106da077))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 8f95e612b19acb77c64938ee723cf2c06ec56bd7 ([link](https://github.com/atypon/test_public/commit/8f95e612b19acb77c64938ee723cf2c06ec56bd7))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid a45b1e8a5995b33272a3658d79fc43160395c447 ([link](https://github.com/atypon/test_public/commit/a45b1e8a5995b33272a3658d79fc43160395c447))

**Pull request merged**
