### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5325](https://github.com/atypon/test_public/pull/5325)), master ([PR#5326](https://github.com/atypon/test_public/pull/5326))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5324](https://github.com/atypon/test_public/pull/5324) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 75cacd21f4a368b3aef5ced0a26dd1f6c552df9d ([link](https://github.com/atypon/test_public/commit/75cacd21f4a368b3aef5ced0a26dd1f6c552df9d))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 422d78edd6f51b52fcad805e17ae0f3339a31264 ([link](https://github.com/atypon/test_public/commit/422d78edd6f51b52fcad805e17ae0f3339a31264))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 3796890bb263a37710fb7e56858d5b3b3614860b ([link](https://github.com/atypon/test_public/commit/3796890bb263a37710fb7e56858d5b3b3614860b))

**Pull request merged**
