### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5150](https://github.com/atypon/test_public/pull/5150)), master ([PR#5151](https://github.com/atypon/test_public/pull/5151))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5149](https://github.com/atypon/test_public/pull/5149) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 6f0a5c011c582771f9cda374bcd6bed5c60d641e ([link](https://github.com/atypon/test_public/commit/6f0a5c011c582771f9cda374bcd6bed5c60d641e))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 62a73112a84d4eccaf7c8575c1c6dee0896dd578 ([link](https://github.com/atypon/test_public/commit/62a73112a84d4eccaf7c8575c1c6dee0896dd578))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid eeed8e92d99600b71cb0ca860bab55f3f5760427 ([link](https://github.com/atypon/test_public/commit/eeed8e92d99600b71cb0ca860bab55f3f5760427))

**Pull request merged**
