### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5066](https://github.com/atypon/test_public/pull/5066)), master ([PR#5067](https://github.com/atypon/test_public/pull/5067))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5065](https://github.com/atypon/test_public/pull/5065) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid e4fd608d37e233fc8faa044e6d61510c4e41de8c ([link](https://github.com/atypon/test_public/commit/e4fd608d37e233fc8faa044e6d61510c4e41de8c))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 22e5c0350112e79649a864744560a359efb9f94c ([link](https://github.com/atypon/test_public/commit/22e5c0350112e79649a864744560a359efb9f94c))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid ef11f9cc73ec07c70bcdd2bc456a84e760264321 ([link](https://github.com/atypon/test_public/commit/ef11f9cc73ec07c70bcdd2bc456a84e760264321))

**Pull request merged**
