### PR TITLE
this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4532](https://github.com/atypon/test_public/pull/4532)), master ([PR#4533](https://github.com/atypon/test_public/pull/4533))

### CODE REVIEW

**Comment by atyponci** [comment]
[Build #1683](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1683/console) completed successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4531](https://github.com/atypon/test_public/pull/4531) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid fbaf2e3133094670286ba945a5e3fbe2442d4356 ([link](https://github.com/atypon/test_public/commit/fbaf2e3133094670286ba945a5e3fbe2442d4356))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid ea57cfce89605225eb50be9c84944fabddf56497 ([link](https://github.com/atypon/test_public/commit/ea57cfce89605225eb50be9c84944fabddf56497))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 95ededdee2fc1f24e4c13d5093c1fb1b9467f061 ([link](https://github.com/atypon/test_public/commit/95ededdee2fc1f24e4c13d5093c1fb1b9467f061))

**Comment by atyponci** [comment]
this.pull.refresh is not a function

**Pull request merged**
