### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5217](https://github.com/atypon/test_public/pull/5217)), master ([PR#5218](https://github.com/atypon/test_public/pull/5218))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5216](https://github.com/atypon/test_public/pull/5216) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 045f89e691480cf8b46ae257bc554c1ef3f4d26b ([link](https://github.com/atypon/test_public/commit/045f89e691480cf8b46ae257bc554c1ef3f4d26b))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid b8a8cc5776593dc8c7df1022454bf7e203992c97 ([link](https://github.com/atypon/test_public/commit/b8a8cc5776593dc8c7df1022454bf7e203992c97))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid b2b7d0958702f0ebb285015237bd9c1163866cba ([link](https://github.com/atypon/test_public/commit/b2b7d0958702f0ebb285015237bd9c1163866cba))

**Pull request merged**
