### PR TITLE
NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: devbranch ([PR#4774](https://github.com/atypon/test_public/pull/4774)), master ([PR#4775](https://github.com/atypon/test_public/pull/4775))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pull:devbranch

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4773](https://github.com/atypon/test_public/pull/4773) complete:

Branch devbranch ([link](https://github.com/atypon/test_public/commits/devbranch)): cid fc0dad1c9e030a3f2ddc873d2e9d88dc116834a4 ([link](https://github.com/atypon/test_public/commit/fc0dad1c9e030a3f2ddc873d2e9d88dc116834a4))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid ff0edda8c12863cb1340b881464bb4a430bbacc2 ([link](https://github.com/atypon/test_public/commit/ff0edda8c12863cb1340b881464bb4a430bbacc2))
Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 124a52ab75f2fa75a685d115e17277a8e8f04bc5 ([link](https://github.com/atypon/test_public/commit/124a52ab75f2fa75a685d115e17277a8e8f04bc5))

**Pull request merged**
