### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5050](https://github.com/atypon/test_public/pull/5050)), master ([PR#5051](https://github.com/atypon/test_public/pull/5051))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5049](https://github.com/atypon/test_public/pull/5049) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 91a6c5471c41b324560c3f88ab0c004b2a0f1596 ([link](https://github.com/atypon/test_public/commit/91a6c5471c41b324560c3f88ab0c004b2a0f1596))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid 3ba4c23e102dfeb6b4a2055b1cdbb06afcc0204e ([link](https://github.com/atypon/test_public/commit/3ba4c23e102dfeb6b4a2055b1cdbb06afcc0204e))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 24fecebb199ad77b1139fa95ce2c2fa43da39054 ([link](https://github.com/atypon/test_public/commit/24fecebb199ad77b1139fa95ce2c2fa43da39054))

**Pull request merged**
