### PR TITLE
[MERGE] PR#4727 into master

### PR DESCRIPTION
**Pull request by atyponci**
#######
parent: ([PR#4727](https://github.com/atypon/test_public/pull/4727))

### CODE REVIEW

**Comment by atyponci** [comment]
This commit cannot be automatically merged due to a complex merge commit, please resolve this manually using the following steps.
**Step 1:** pull changes
```
git fetch origin && git checkout 4727__conflict__master && git cherry-pick 164811067061b24e8a03865f73b8aefd19643f9c
```
**Step 2:** Resolve the conflicts and then run `git add -A && git cherry-pick --continue`  to complete the cherry-pick
**Step 3:** Push the changes back to GitHub with `git push origin 4727__conflict__master`
**Step 4:** Comment on this PR with "continue" when the changes look correct

**Comment by opsmail** [comment]
continue

**Comment by atyponci** [comment]
Executed step successfully

**Comment by atyponci** [comment]
[Build #1799](https://acjenkins.atypon.com/job/githubbot-unittests-test_public/1799/console) completed successfully

**Pull request merged**
