### PR TITLE
AUTO NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#5084](https://github.com/atypon/test_public/pull/5084)), master ([PR#5085](https://github.com/atypon/test_public/pull/5085))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by atyponci** [comment]
Failed to create merge pull for nonexistantBranch failed with error: Failed to create merge branches: Error executing 'cd /opt/data/repos/test_public && git checkout nonexistantBranch'
STDERR:
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.: Command failed: cd /opt/data/repos/test_public && git checkout nonexistantBranch
error: pathspec 'nonexistantBranch' did not match any file(s) known to git.

**Comment by atyponci** [comment]
The create-pulls step has failed, please collect the appropriate information and then use `resetpulls` to try again

**Comment by opsmail** [comment]
resetpulls

**Comment by atyponci** [comment]
Executed command successfully

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#5083](https://github.com/atypon/test_public/pull/5083) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid 182842dc956bd9667905681560445a14d9618748 ([link](https://github.com/atypon/test_public/commit/182842dc956bd9667905681560445a14d9618748))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid c106022ea92253c7efe9507dd37bbe6cc614a2be ([link](https://github.com/atypon/test_public/commit/c106022ea92253c7efe9507dd37bbe6cc614a2be))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid 3f400b7552aa5ae64143d3e50e39cc711679202a ([link](https://github.com/atypon/test_public/commit/3f400b7552aa5ae64143d3e50e39cc711679202a))

**Pull request merged**
