### PR TITLE
NOSQUASH NOBUILD this is a feature

### PR DESCRIPTION
**Pull request by atyponci**
test description

#######
generatedPulls: SG-1730 ([PR#4615](https://github.com/atypon/test_public/pull/4615)), master ([PR#4616](https://github.com/atypon/test_public/pull/4616))

### CODE REVIEW

**Comment by atyponci** [comment]
Ready to create merge pulls. Comment on this ticket with "pulls" to instruct the bot to create pull requests with your change on all of the other destination branches. This functionality is replacing the cherry-pick script and offers an increased degree of reliability, automation, and ease of use. 

For more information, read the [Atypon GitHub Bot Confluence page](https://confluence.atypon.com/display/EN/Atypon+GitHub+Bot).

**Comment by opsmail** [comment]
pulls

**Comment by atyponci** [comment]
This pull request is ready to merge, comment 'merge' to automatically merge.

**Comment by opsmail** [comment]
merge

**Comment by atyponci** [comment]
[GitBot] Merge of [PR#4614](https://github.com/atypon/test_public/pull/4614) complete:

Branch SG-1730 ([link](https://github.com/atypon/test_public/commits/SG-1730)): cid c06a43aa19c0323cf2f9dfa8d1079d0e4b361a2b ([link](https://github.com/atypon/test_public/commit/c06a43aa19c0323cf2f9dfa8d1079d0e4b361a2b))
Branch master ([link](https://github.com/atypon/test_public/commits/master)): cid f307d310d17c4a5056861927a91851352631e562 ([link](https://github.com/atypon/test_public/commit/f307d310d17c4a5056861927a91851352631e562))
Branch SG-1720 ([link](https://github.com/atypon/test_public/commits/SG-1720)): cid d8d90cd2065a87fe3649faa967f1de12dccdb2bf ([link](https://github.com/atypon/test_public/commit/d8d90cd2065a87fe3649faa967f1de12dccdb2bf))

**Pull request merged**
